import { cn } from "@/lib/utils";
import { Space_Grotesk } from "next/font/google";
import Providers from "@/store/Providers";
import NextTopLoader from "nextjs-toploader";
import { Toaster } from "react-hot-toast";
import "./globals.css";
import Navbar from "@/components/NavBar";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Recypter",
  description: "Generated by create next app",
};

// Import Space Grotesk font
const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  display: "swap",
});

export default async function RootLayout({ children }) {
  return (
    <Providers>
      <html lang="en">
        <body
          className={cn(
            "min-h-screen bg-background text-foreground",
            spaceGrotesk.className
          )}
        >
          <Toaster position="top-center" reverseOrder={false} />
          <NextTopLoader
            color="#5E17EB"
            initialPosition={0.08}
            crawlSpeed={400}
            height={3}
            crawl={true}
            showSpinner={false}
            easing="ease"
            speed={200}
            shadow="0 0 10px #2299DD,0 0 5px #2299DD"
          />
          <div className="w-full shadow-md shadow-[#88888821]">
            <Navbar />
          </div>
          <main className="">{children}</main>
          {/* <div className="w-full shadow-md shadow-[#88888821]">
            <Footer />
          </div> */}
        </body>
      </html>

      {/* //hello */}
    </Providers>
  );
}
